version: '3.3'

services:
  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 licensing_platform.wsgi --workers=4
    environment:
      - DEBUG: ${DEBUG}
      - DATABASE_NAME: ${DATABASE_NAME}
      - DATABASE_USER: ${DATABASE_USER}
      - DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      - HOST_ENDPOINT: ${HOST_ENDPOINT}
      - REDIS_LOCATION: ${REDIS_LOCATION}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    networks:
      - django-network

  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django-network

networks:
  django-network:
    name: django-network

volumes:
  media_volume:
  static_volume: