version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 licensing_platform.wsgi:application
    volumes:
      - static_volume:/home/licensing-as-a-platform/web/staticfiles
      - media_volume:/home/licensing-as-a-platform/web/mediafiles
    expose:
      - 8000
  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/home/licensing-as-a-platform/web/staticfiles
      - media_volume:/home/licensing-as-a-platform/web/mediafiles
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: